/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SkSpinner {
    }
    interface SkStockFinder {
    }
    interface SkStockPrice {
        "stockSymbol": string;
    }
}
export interface SkStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSkStockFinderElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSkSpinnerElement extends Components.SkSpinner, HTMLStencilElement {
    }
    var HTMLSkSpinnerElement: {
        prototype: HTMLSkSpinnerElement;
        new (): HTMLSkSpinnerElement;
    };
    interface HTMLSkStockFinderElementEventMap {
        "skSymbolSelected": string;
    }
    interface HTMLSkStockFinderElement extends Components.SkStockFinder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSkStockFinderElementEventMap>(type: K, listener: (this: HTMLSkStockFinderElement, ev: SkStockFinderCustomEvent<HTMLSkStockFinderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSkStockFinderElementEventMap>(type: K, listener: (this: HTMLSkStockFinderElement, ev: SkStockFinderCustomEvent<HTMLSkStockFinderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSkStockFinderElement: {
        prototype: HTMLSkStockFinderElement;
        new (): HTMLSkStockFinderElement;
    };
    interface HTMLSkStockPriceElement extends Components.SkStockPrice, HTMLStencilElement {
    }
    var HTMLSkStockPriceElement: {
        prototype: HTMLSkStockPriceElement;
        new (): HTMLSkStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sk-spinner": HTMLSkSpinnerElement;
        "sk-stock-finder": HTMLSkStockFinderElement;
        "sk-stock-price": HTMLSkStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SkSpinner {
    }
    interface SkStockFinder {
        "onSkSymbolSelected"?: (event: SkStockFinderCustomEvent<string>) => void;
    }
    interface SkStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sk-spinner": SkSpinner;
        "sk-stock-finder": SkStockFinder;
        "sk-stock-price": SkStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sk-spinner": LocalJSX.SkSpinner & JSXBase.HTMLAttributes<HTMLSkSpinnerElement>;
            "sk-stock-finder": LocalJSX.SkStockFinder & JSXBase.HTMLAttributes<HTMLSkStockFinderElement>;
            "sk-stock-price": LocalJSX.SkStockPrice & JSXBase.HTMLAttributes<HTMLSkStockPriceElement>;
        }
    }
}
